##########################################################################
# $Id: Makefile,v 1.9 2002/11/17 03:31:50 corsaro Exp $
##########################################################################

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Macros.GNU

TARGET := $(RTJP_HOME)/bin/AllocTimeTest
MAINCLASS := edu.uci.ece.doc.rtjperf.mem.AllocTimeTest 

SRCS := $(wildcard $(SRC_DIR)/mem/*.java)
SRCS += $(wildcard $(SRC_DIR)/util/*.java)

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Rules.GNU
