##########################################################################
# $Id: Makefile,v 1.4 2003/03/29 19:25:58 corsaro Exp $
##########################################################################

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Macros.GNU

TARGET := $(RTJP_HOME)/bin/YieldTest
MAINCLASS := edu.uci.ece.doc.rtjperf.thread.YieldTest 

SRCS := $(wildcard $(SRC_DIR)/thread/*.java)
SRCS += $(wildcard $(SRC_DIR)/util/*.java)
SRCS += $(wildcard $(SRC_DIR)/sys/*.java)

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Rules.GNU
