##########################################################################
# $Id: Makefile,v 1.2 2002/12/14 02:04:23 corsaro Exp $
##########################################################################

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Macros.GNU

TARGET := $(RTJP_HOME)/bin/MonitorTest
MAINCLASS := edu.uci.ece.doc.rtjperf.synch.MonitorTest 

SRCS := $(SRC_DIR)/synch/MonitorTest.java
SRCS += $(wildcard $(SRC_DIR)/util/*.java)
SRCS += $(wildcard $(SRC_DIR)/sys/*.java)

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Rules.GNU
