##########################################################################
# $Id: Makefile,v 1.1 2002/11/30 23:33:52 corsaro Exp $
##########################################################################

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Macros.GNU

TARGET := $(RTJP_HOME)/bin/ScopedMemoryTiming
MAINCLASS := edu.uci.ece.doc.rtjperf.mem.timing.ScopedMemoryTimingTest 

SRCS := $(wildcard $(SRC_DIR)/mem/*.java)
SRCS += $(wildcard $(SRC_DIR)/mem/timing/*.java)
SRCS += $(wildcard $(SRC_DIR)/util/*.java)

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Rules.GNU
