##########################################################################
# $Id: Makefile,v 1.1 2002/12/13 05:54:50 corsaro Exp $
##########################################################################

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Macros.GNU

TARGET := $(RTJP_HOME)/bin/AEHTest
MAINCLASS := edu.uci.ece.doc.rtjperf.asynch.DispatchDelayTestLauncher 

SRCS := $(wildcard $(SRC_DIR)/asynch/*.java)
SRCS += $(wildcard $(SRC_DIR)/util/*.java)
SRCS += $(wildcard $(SRC_DIR)/sys/*.java)

include $(RTJP_HOME)/src/edu/uci/ece/doc/rtjperf/Rules.GNU
